// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Note struct {
	ID      string `json:"id"`
	Title   string `json:"title"`
	Content string `json:"content"`
	User    *User  `json:"user"`
}

type User struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

type NewNote struct {
	Title    string `json:"title"`
	Content  string `json:"content"`
	UserName string `json:"userName"`
}
